하림 : 2-1 구현
codesquad-members-2023/swift-pokergame pull request #10
Opened 2023-03-13 08:51 UTC by harimrim

- (width / 7)  - 2.5 및 posX += width + 2.5 코드로 card 양 옆에 padding이 있는 것 같은 느낌을 주었습니다
- card의 크기를 화면과 맞추기 위해 view.bounds.width 를 사용하였고, 세로와 가로의 비율을 맞추기 위해서 높이 = 가로 * 1.27 의 값을 사용하였습니다.

2023-03-13 08:56 UTC, godrm commented
리뷰할 분량이 조금 있어서 읽어보는 동안, 우선 오늘 공유한 리뷰 가이드에 대한 영상이나 자료를 보고 PR 메시지 좀 수정해주세요. 

학습 계획과 맥락이 다른 프로젝트 생성하고 구현한 것도 PR을 분리하는 게 좋을 것 같습니다  
예를 들어 학습 계획만 승인하고 싶은데, 프로젝트와 관련된 게 추가되어 있으니까 승인이 안될 수도 있습니다. 이렇게 작업 단위가 서로 다른 업무라고 할 수 있습니다.

2023-03-13 09:17 UTC, godrm requested changes
계획과 구현을 합쳐서 보낸 상태라 계획마저 승인되지 않았습니다
다음 내용들 확인하거나 개선한 다음에 승인하고 머지하도록 하겠습니다

2023-03-13 09:17 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +    }
커밋 로그 상으로는 프로젝트 생성과 gitignore를 추가한 것으로 되어 있는데
커밋한 파일에는 gitignore 파일을 수정한 내역이 없습니다. 어떻게 된걸까요?

2023-03-13 09:17 UTC, godrm commented on PokerGameApp/PokerGameApp/GameBoardViewController.swift
> +        self.view.backgroundColor = UIColor(patternImage: UIImage(named: "bg_pattern")!)
패턴을 컬러로 지정한 부분은 좋습니다. 배경 UIImage에서 사용한 강제 언래핑은 좋은 습관은 아닙니다
혹시라도 이미지 이름이 잘못되거나 불러오지 못하면 여기서 앱이 멈추고 죽어버립니다. 배경 이미지가 없으면 앱이 죽어야만 하는걸까요?
옵셔널 언래핑을 안전하게 처리하는 방법에 대해 확인해서 개선해보세요

2023-03-13 09:17 UTC, godrm commented on PokerGameApp/PokerGameApp/GameBoardViewController.swift
> +            var posY: CGFloat = 50
- posX, posX는 억지로 줄여쓴 단어처럼 보입니다. 
- posX 뒤에 타입에는 공백이 없는데, posY 뒤에는 공백이 있습니다
- width는 무엇의 width일까 좀 더 구체적으로 콕 집어도 좋겠습니다
- 위에 나오는 숫자들 2.5, 7, 0, 6, 50도 의미가 있는 거니까 어떤 의도인지 표현하는 상수로 선언해보세요

2023-03-13 09:17 UTC, godrm commented on PokerGameApp/PokerGameApp/GameBoardViewController.swift
> +            }()
- 이렇게 UIImageView{}() 형태로 생성하는 것은 인스턴스를 생성하고 속성을 넣어주는 것과 어떤 차이가 있나요?
- `let cardBackImage = UIImage(named: "card-back")!` 부분은 같은 뒷면 이미지 일텐데 7번 생성하지 않고 한 번만 생성해도 되지 않을까요?

2023-03-13 09:17 UTC, godrm commented on PokerGameApp/PokerGameApp/Assets.xcassets/bg_pattern.imageset/Contents.json
> +      "scale" : "1x"
이건 코드가 아니지만 지난 수업에 잠깐 언급했던 내용입니다. 이미지 추가할 때 배율에 대해 조사해보고 어떤 배율이 필요한지 확인해보세요

2023-03-15 02:47 UTC, godrm commented
@harimrim 수정한 게 어제 올라오지 않았네요! 과정에 대해 댓글이라도 남겨주면 어떨까 싶습니다.

2023-03-15 03:13 UTC, harimrim commented on PokerGameApp/PokerGameApp/Assets.xcassets/bg_pattern.imageset/Contents.json
> +      "scale" : "1x"
픽셀과 포인트 때문에 배율이 필요하다는 내용을 잠깐 깜빡했습니다 ... 슈퍼 레티나 디스플레이는 3배율이 필요하네요..!

2023-03-15 03:29 UTC, harimrim commented on PokerGameApp/PokerGameApp/GameBoardViewController.swift
> +            }()
- UIImageView{}() 형태는 클로저를 사용해서 인스턴스를 생성하는 방식이라 인스턴스 생성과 초기화를 한번에 해서 편리하다고 생각했는데 코드 가독성이 인스턴스를 생성하고 속성을 넣어주는 것보다는 안좋은 것 같습니다.
- 말씀하신 것처럼 한번만 생성하는게 불필요한 낭비를 줄이는 방향인 것 같습니다..! 수정했습니다

2023-03-15 03:31 UTC, harimrim commented on PokerGameApp/PokerGameApp/GameBoardViewController.swift
> +        self.view.backgroundColor = UIColor(patternImage: UIImage(named: "bg_pattern")!)
저도 모르게 당연히 이미지가 있다는 생각에 강제 언래핑을 사용했습니다... 좀 더 안전한 동작을 위해서 옵셔널 바인딩을 통해 언래핑 하는 방향으로 수정했습니다!

2023-03-15 03:33 UTC, harimrim commented on PokerGameApp/PokerGameApp/ViewController.swift
> +    }
Clone으로 추가된 gitignore를 제가 생성한 파일로 착각했습니다... 확인하고 내용 수정했습니다 ㅠㅠ

2023-03-15 04:01 UTC, harimrim commented
모르는 부분이 많아서 수정이 늦어졌습니다.. 피드백 해주신 부분 수정해서 푸쉬하였습니다..!

2023-03-15 05:46 UTC, godrm approved these changes
확인했습니다

2023-03-15 05:46 UTC, merged